version: '3.9'

services:
  postgres:
    container_name: pg-bckndcodechallenge
    image: postgres:14.1-alpine
    env_file: .env
    environment:
      POSTGRES_PASSWORD: ${DBDEV_PASSWORD}
      PGPORT: "${DBDEV_PORT}"
      POSTGRES_USER: "${DBDEV_USERNAME}"
      POSTGRES_DB: "${DBDEV_DATABASE}"
    volumes:
      - pg-bckndcodechallenge:/var/lib/postgresql/data
    ports:
      - ${DBDEV_PORT}:${DBDEV_PORT}
    network_mode: host
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DBDEV_USERNAME} -d ${DBDEV_DATABASE}"]
      interval: 3s
      timeout: 3s
      retries: 5
    
  bckndcodechallenge:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bckndcodechallenge
    command: bash init.sh
    env_file: .env
    volumes:
      - .:/code
    depends_on:
      postgres:
        condition: service_healthy
    network_mode: host

volumes:
  pg-bckndcodechallenge: